#!/bin/sh
# shellcheck disable=SC1090,SC1091
. "$(dirname "$0")/_/husky.sh"

PATH=$PATH:/usr/local/bin

echo 'NOTE: If node/npm/yarn is not found, you may need to run brew link for your specific node version'

yarn lint:staged
